import './styles.css';

type Transporter={name:string;shipments:number;avg_qty_kg:number|null;min_qty_kg:number|null;max_qty_kg:number|null;avg_tat_days:number|null;median_tat_days:number|null;avg_distance_km:number|null;last_used:string|null};
type Lane={pickup:string;delivery:string;transporter:string;shipments:number;avg_qty_kg:number|null;min_qty_kg:number|null;max_qty_kg:number|null;avg_tat_days:number|null;median_tat_days:number|null;avg_distance_km:number|null;last_used:string|null};
type Base={meta:{source:string;source_rows:number;ptl_shipments:number;usable_ptl_shipments:number;transporters:number;exact_pincode_lanes:number};transporters:Transporter[];lanes:Lane[]};
type Network={name:string;scope:string;regions:string[];min_kg:number|null;max_kg:number|null;contact:string;email:string;source:string;evidence:string;note:string};
const NETWORK:Network[]=[
{name:'DNS Logistics',scope:'Pan India',regions:['North','West','South','East'],min_kg:1,max_kg:5000,contact:'+91 90827 36097',email:'info@dnslogistic.com',source:'https://www.dnslogistic.com/services/ptl',evidence:'Official PTL page',note:'Public B2B PTL network; exact pincode and special cargo acceptance must be confirmed.'},
{name:'Fast Trackon Logistics',scope:'Pan India',regions:['North','West','South','East'],min_kg:50,max_kg:5000,contact:'+91 88288 81414',email:'support@fasttrackonlogistics.com',source:'https://www.fasttrackonlogistics.com/services/ptl',evidence:'Official PTL page',note:'Published pan-India PTL network; exact pincode should be confirmed.'},
{name:'CTC India',scope:'Pan India',regions:['North','West','South','East'],min_kg:null,max_kg:null,contact:'+91 9873294018',email:'info@ctcipl.com',source:'https://www.ctcipl.com/services/part-truck-load-ptl',evidence:'Official PTL page',note:'Pan-India PTL routes published; exact pincode should be confirmed.'},
{name:'Bombay Kandla Transport',scope:'Pan India',regions:['North','West','South','East'],min_kg:null,max_kg:null,contact:'sales@bombaykandla.com',email:'sales@bombaykandla.com',source:'https://bktpl.co.in/',evidence:'Official company site',note:'Pan-India branch network with PTL/industrial transport; exact lane should be confirmed.'},
{name:'WheelsEye PTL',scope:'Pan India',regions:['North','West','South','East'],min_kg:5,max_kg:3000,contact:'Public contact via official site',email:'',source:'https://wheelseye.com/ptl',evidence:'Official PTL page',note:'PTL marketplace/network option; partner selection is route dependent.'},
{name:'City Cargo PTL',scope:'Pan India',regions:['North','West','South','East'],min_kg:null,max_kg:null,contact:'Public contact via official site',email:'',source:'https://www.citycargo.city/ptl',evidence:'Official PTL page',note:'Network marketplace; exact pincode and acceptance should be confirmed.'},
{name:'URTC Group',scope:'Regional',regions:['West','Central','East'],min_kg:null,max_kg:null,contact:'Public contact via official site',email:'',source:'https://www.urtcgroup.com/services/part-load-transport-services/',evidence:'Official PTL page',note:'Gujarat/Maharashtra/central-east corridor lead; verify exact pincode.'},
{name:'Superior Transways',scope:'Regional',regions:['West','North','South'],min_kg:null,max_kg:null,contact:'+91 7770026141',email:'superiortransways18@gmail.com',source:'https://superiortransways.com/part-load-transportation/',evidence:'Official PTL page',note:'West-linked regional PTL option; verify exact pincode.'},
{name:'Jai Ambey Roadline',scope:'Regional',regions:['North','West','Central'],min_kg:null,max_kg:null,contact:'Public contact via official site',email:'',source:'https://www.jaiambeyroadline.com/network',evidence:'Official network page',note:'Network lead; use as regional option and verify exact lane.'},
{name:'Mukund Logistics',scope:'Regional',regions:['North','Central'],min_kg:null,max_kg:null,contact:'Public contact via official site',email:'',source:'https://www.mukundlogistic.com/ncr/services/part-load/',evidence:'Official part-load page',note:'Delhi NCR/North India lead; verify destination pincode.'},
{name:'Malwa Golden Logistics',scope:'Regional',regions:['North'],min_kg:null,max_kg:null,contact:'+91 94637 37337',email:'info@malwagolden.com',source:'https://www.malwagolden.com/',evidence:'Official company site',note:'Punjab/Haryana/Delhi-NCR lead; verify exact lane.'},
{name:'AKT Logistics',scope:'Regional',regions:['North'],min_kg:null,max_kg:null,contact:'+91 9720253030',email:'admin@aktlogistics.co.in',source:'https://aktlogistics.co.in',evidence:'Official company site',note:'North India lead; verify exact pincode.'},
{name:'Master Ashirwad Roadways',scope:'Regional',regions:['North'],min_kg:null,max_kg:null,contact:'05944 240107',email:'master_ashirwadroadways@yahoo.com',source:'https://masterashirwad.com',evidence:'Official company site',note:'North India lead; verify exact lane and PTL fit.'},
{name:'Unique Carriers',scope:'Regional',regions:['North'],min_kg:null,max_kg:null,contact:'0172-4788763',email:'mohali@uniquecarriers.in',source:'https://uniquecarriers.in',evidence:'Official company site',note:'North India network; exact PTL serviceability should be confirmed.'},
{name:'SRL Carriers',scope:'Regional',regions:['North'],min_kg:null,max_kg:null,contact:'+91 95377 86932',email:'mumbai@srlcarriers.com',source:'https://srlcarriers.com',evidence:'Official company site',note:'North India corridor lead; verify exact pincode and PTL fit.'},
{name:'Narsik Logistics',scope:'Regional',regions:['North','West','Central'],min_kg:null,max_kg:null,contact:'+91 9929031702',email:'info@narsiklogistics.com',source:'https://narsiklogistics.com',evidence:'Official company site',note:'Rajasthan/Delhi-NCR/UP/MP/Gujarat corridor lead; verify exact pincode.'},
{name:'Puran Bharat Road Carriers',scope:'Regional',regions:['North','West'],min_kg:null,max_kg:null,contact:'+91 9560622819',email:'madhavyadav@pbrc.co.in',source:'https://pbrc.co.in',evidence:'Official company site',note:'North/West corridor lead; verify exact pincode and PTL fit.'},
{name:'ARC Logistics',scope:'Pan India',regions:['North','West','South','East','Central'],min_kg:null,max_kg:null,contact:'+91 7972007515',email:'',source:'https://www.arclogistics.in/part-truck-load-services.php',evidence:'Official PTL page',note:'Part-truck-load option; verify exact pincode.'},
{name:'Gati',scope:'Pan India',regions:['North','West','South','East'],min_kg:null,max_kg:null,contact:'Public contact via official site',email:'',source:'https://www.gati.com/',evidence:'Official company site',note:'National surface network; verify exact PTL/LTL lane and weight acceptance.'},
{name:'Safexpress',scope:'Pan India',regions:['North','West','South','East'],min_kg:null,max_kg:null,contact:'Public contact via official site',email:'',source:'https://www.safexpress.com/',evidence:'Official company site',note:'National B2B surface network; route and cargo acceptance should be confirmed.'},
{name:'V-Trans',scope:'Pan India',regions:['North','West','South','East'],min_kg:null,max_kg:null,contact:'Public contact via official site',email:'',source:'https://www.vtransgroup.com/',evidence:'Official company site',note:'National surface network; exact PTL lane should be confirmed.'},
{name:'VRL Logistics',scope:'Pan India',regions:['North','West','South','East'],min_kg:null,max_kg:null,contact:'Public contact via official site',email:'',source:'https://www.vrlgroup.in/',evidence:'Official company site',note:'National surface network; exact PTL lane and cargo acceptance should be confirmed.'},
{name:'TCI Express',scope:'Pan India',regions:['North','West','South','East'],min_kg:null,max_kg:null,contact:'Public contact via official site',email:'',source:'https://www.tciexpress.in/',evidence:'Official company site',note:'National express network; use as public-network lead and verify exact lane.'}
];
const app=document.querySelector<HTMLDivElement>('#app')!;
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const fmt=(v:number|null|undefined)=>v==null?'—':Math.round(v).toLocaleString('en-IN');
const fmt1=(v:number|null|undefined)=>v==null?'—':v.toLocaleString('en-IN',{maximumFractionDigits:1});
const esc=(v:string)=>v.replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]!));
const fit=(q:number,min:number|null,max:number|null)=>(min==null||q>=min)&&(max==null||q<=max);
const region=(pin:string)=>{const n=Number(pin[0]);return n===1||n===2?'North':n===3||n===4?'West':n===5||n===6?'South':n===7||n===8?'East':'Central'};
function shell(){app.innerHTML=`<div class="shell"><aside class="side"><div class="brand"><b>◆ ATOMGRID</b><small>SMART TRANSPORT SOURCING</small></div><div class="nav active">Transporter Finder</div><div class="side-foot">Internal use only</div></aside><main class="main"><header class="top"><div><span class="kicker">SUPPLY CHAIN INTELLIGENCE</span><h2>Transporter Finder</h2></div><div class="live">● Live</div></header><section class="content"><div class="hero"><div><span class="eyebrow">HISTORICAL + ONLINE NETWORK</span><h1>Find transporter options for your lane.</h1><p>Start with Atomgrid's historical PTL movements, then add public regional and pan-India transporter options.</p></div><div class="snapshot"><span>PTL shipments</span><strong id="ptl">—</strong><small id="meta">Loading base data…</small></div></div><section class="search"><label>Pickup Pincode<input id="pickup" maxlength="6" inputmode="numeric" placeholder="394116"></label><button id="swap" class="swap">↔</button><label>Delivery Pincode<input id="delivery" maxlength="6" inputmode="numeric" placeholder="502279"></label><label>Quantity (KG)<input id="qty" type="number" min="1" placeholder="850"></label><button id="find" class="primary">Find Transporters <span>→</span></button></section><div class="smartbar"><div>✦</div><div><b>Smart sourcing</b><span>Exact lane → quantity fit → wider historical network → public regional/pan-India options.</span></div><select id="mode"><option value="combined">Combined</option><option value="history">Historical only</option><option value="online">Online only</option></select></div><section class="summary" id="summary"></section><div class="section-head"><div><span class="eyebrow">RESULTS</span><h3 id="title">Enter a route and quantity</h3><p id="subtitle">Your sourcing options will appear here.</p></div><div class="count" id="count">0 options</div></div><div id="results"></div><div class="provenance"><b>Data basis:</b> historical results come from the Atomgrid Domestic MIS PTL history. Public options are from company websites and are leads, not proof of exact pincode serviceability.</div></section></main></div>`;
$('find').addEventListener('click',search);$('swap').addEventListener('click',()=>{const p=$<HTMLInputElement>('pickup'),d=$<HTMLInputElement>('delivery');[p.value,d.value]=[d.value,p.value];search()});['pickup','delivery','qty'].forEach(id=>$(id).addEventListener('keydown',e=>{if((e as KeyboardEvent).key==='Enter')search()}));$('mode').addEventListener('change',search);}
async function load(){try{const r=await fetch('/api/data');if(!r.ok)throw new Error(`HTTP ${r.status}`);const b=await r.json() as Base;$('ptl').textContent=fmt(b.meta.ptl_shipments);$('meta').textContent=`${b.meta.transporters} transporters • ${b.meta.exact_pincode_lanes} exact lanes`;(window as any).BASE=b;renderEmpty()}catch(e){console.error(e);$('meta').textContent='Base dataset unavailable';$('results').innerHTML='<div class="empty">The historical MIS could not be loaded. Please retry in a moment.</div>';}}
function renderEmpty(){ $('summary').innerHTML='';$('results').innerHTML='<div class="empty">Enter pickup pincode, delivery pincode and quantity to see transporter options.</div>';}
function scoreLane(l:any,q:number,maxS:number,maxD:number){return Math.round(Math.min(100,40+(fit(q,l.min_qty_kg,l.max_qty_kg)?25:0)+(maxS?20*l.shipments/maxS:0)+(l.avg_tat_days!=null?Math.max(1,10-l.avg_tat_days):3)+(maxD&&l.avg_distance_km!=null?Math.max(1,5-3*l.avg_distance_km/maxD):2)))}
function search(){const base=(window as any).BASE as any;if(!base)return;const p=$<HTMLInputElement>('pickup').value.trim(),d=$<HTMLInputElement>('delivery').value.trim(),q=Number($<HTMLInputElement>('qty').value||0),mode=$<HTMLSelectElement>('mode').value;if(!/^\d{6}$/.test(p)||!/^\d{6}$/.test(d)||q<=0){renderEmpty();return}const exact=base.lanes.filter((x:any)=>x.pickup===p&&x.delivery===d);const maxS=Math.max(1,...exact.map((x:any)=>x.shipments));const maxD=Math.max(1,...exact.map((x:any)=>x.avg_distance_km||0));let html='';let h=0,o=0;let msg='';if(mode!=='online'){const matches=exact.filter((x:any)=>fit(q,x.min_qty_kg,x.max_qty_kg)).map((x:any)=>({...x,score:scoreLane(x,q,maxS,maxD)})).sort((a:any,b:any)=>b.score-a.score);if(matches.length){h=matches.length;msg=`${matches.length} exact historical option${matches.length===1?'':'s'} match the entered quantity.`;html+=`<div class="tag hist">ATOMGRID HISTORICAL — EXACT LANE</div>${matches.slice(0,12).map((x:any,i:number)=>histCard(x,q,i+1,'Exact lane')).join('')}`}else if(exact.length){h=exact.length;msg='Exact lane exists, but the quantity is outside historical ranges.';html+=`<div class="tag warn">ATOMGRID HISTORICAL — QUANTITY OUTSIDE RANGE</div>${exact.sort((a:any,b:any)=>b.shipments-a.shipments).map((x:any,i:number)=>histCard({...x,score:scoreLane(x,q,maxS,maxD)},q,i+1,'Exact lane • verify qty')).join('')}`}else{const wider=base.transporters.filter((x:any)=>fit(q,x.min_qty_kg,x.max_qty_kg)).slice(0,12);h=wider.length;msg='No exact lane history. Showing broader historical transporter network options.';html+=`<div class="tag hist">ATOMGRID HISTORICAL — NETWORK OPTIONS</div>${wider.map((x:any,i:number)=>networkCard(x,q,i+1)).join('')}`}}
if(mode!=='history'){const online=NETWORK.map(x=>({...x,score:(x.scope==='Pan India'?45:((x.regions.includes(region(p))?25:0)+(x.regions.includes(region(d))?25:0)))+((x.min_kg==null||q>=x.min_kg)?5:0)+((x.max_kg==null||q<=x.max_kg)?5:0)})).filter(x=>x.score>=35).sort((a,b)=>b.score-a.score).slice(0,10);o=online.length;html+=`<div class="tag online">PUBLIC NETWORK — REGIONAL + PAN INDIA</div>${online.map((x,i)=>onlineCard(x,q,i+1,p,d)).join('')}`}
const total=h+o;$('title').textContent=`${total} transporter options`;$('subtitle').textContent=`${p} → ${d} • ${fmt(q)} KG`;$('count').textContent=`${total} options`;$('summary').innerHTML=`<div class="summary-icon">✦</div><div><b>SMART SOURCING VIEW</b><strong>${esc(msg||'Combined transporter search')}</strong><span>Historical evidence and public-network leads are separated.</span></div>`;$('results').innerHTML=html||'<div class="empty">No matching option found. Try another lane or check the pincode.</div>'}
function histCard(x:any,q:number,rank:number,status:string){return `<article class="card featured"><div class="rank">#${rank}</div><div class="row"><div><h4>${esc(x.transporter)}</h4><p>${x.pickup} → ${x.delivery}</p></div><div class="score"><b>${x.score}</b><span>SMART<br>MATCH</span></div></div><div class="badges"><span class="badge green">${esc(status)}</span><span class="badge">${fit(q,x.min_qty_kg,x.max_qty_kg)?'Quantity compatible':'Quantity outside history'}</span></div><div class="metrics"><span><small>Shipments</small><b>${fmt(x.shipments)}</b></span><span><small>TAT</small><b>${x.avg_tat_days==null?'—':x.avg_tat_days.toFixed(1)} days</b></span><span><small>Distance</small><b>${fmt1(x.avg_distance_km)} km</b></span><span><small>Historic qty</small><b>${fmt(x.min_qty_kg)}–${fmt(x.max_qty_kg)} KG</b></span></div><div class="why"><b>Why shown</b><span>Exact historical lane</span><span>${fit(q,x.min_qty_kg,x.max_qty_kg)?'Quantity fits historical range':'Quantity differs from history'}</span><span>${x.shipments>3?'Repeated historical usage':'Historical use recorded'}</span></div><div class="foot">Last used ${esc(x.last_used||'—')}</div></article>`}
function networkCard(x:any,q:number,rank:number){return `<article class="card"><div class="rank">#${rank}</div><div class="row"><div><h4>${esc(x.name)}</h4><p>Historical network option</p></div><div class="score green-score"><b>${Math.min(85,Math.round(25+(x.shipments>0?35:0)+(x.avg_tat_days!=null?Math.max(3,15-x.avg_tat_days*2):5)))}</b><span>NETWORK<br>FIT</span></div></div><div class="badges"><span class="badge blue">Historical network</span><span class="badge">${fit(q,x.min_qty_kg,x.max_qty_kg)?'Quantity compatible':'Verify quantity'}</span></div><div class="metrics"><span><small>Shipments</small><b>${fmt(x.shipments)}</b></span><span><small>TAT</small><b>${x.avg_tat_days==null?'—':x.avg_tat_days.toFixed(1)} days</b></span><span><small>Avg distance</small><b>${fmt1(x.avg_distance_km)} km</b></span><span><small>Historic qty</small><b>${fmt(x.min_qty_kg)}–${fmt(x.max_qty_kg)} KG</b></span></div><div class="why"><b>Why shown</b><span>Used elsewhere in Atomgrid PTL history</span><span>Entered quantity fits historical range</span></div><div class="foot">Last used ${esc(x.last_used||'—')}</div></article>`}
function onlineCard(x:any,q:number,rank:number,p:string,d:string){const weightFit=(x.min_kg==null||q>=x.min_kg)&&(x.max_kg==null||q<=x.max_kg);const basis=x.scope==='Pan India'?'Pan-India published network':`${region(p)} → ${region(d)} regional fit`;return `<article class="card online-card"><div class="rank">#${rank}</div><div class="row"><div><h4>${esc(x.name)}</h4><p>${esc(basis)}</p></div><div class="score green-score"><b>${x.score}</b><span>NETWORK<br>FIT</span></div></div><div class="badges"><span class="badge blue">Public source</span><span class="badge amber">${weightFit?'Weight range fit':'Verify weight'}</span></div><div class="metrics"><span><small>Coverage</small><b>${esc(x.scope)}</b></span><span><small>Regions</small><b>${esc(x.regions.join(' • '))}</b></span><span><small>Contact</small><b>${esc(x.contact)}</b></span><span><small>Evidence</small><b>${esc(x.evidence)}</b></span></div><div class="why"><b>Why shown</b><span>${esc(x.note)}</span><span>Exact pincode coverage is not inferred from region alone.</span></div><div class="foot"><a href="${esc(x.source)}" target="_blank" rel="noreferrer">Official source →</a>${x.email?`<span>${esc(x.email)}</span>`:''}</div></article>`}
shell();load();
