import './styles.css';

type Transporter={name:string;shipments:number;avg_qty_kg:number|null;min_qty_kg:number|null;max_qty_kg:number|null;avg_tat_days:number|null;median_tat_days:number|null;avg_distance_km:number|null;last_used:string|null};
type Lane={pickup:string;delivery:string;transporter:string;shipments:number;avg_qty_kg:number|null;min_qty_kg:number|null;max_qty_kg:number|null;avg_tat_days:number|null;median_tat_days:number|null;avg_distance_km:number|null;last_used:string|null};
type Base={meta:{source:string;source_rows:number;ptl_shipments:number;usable_ptl_shipments:number;transporters:number;exact_pincode_lanes:number};transporters:Transporter[];lanes:Lane[]};
type Cargo='General'|'Chemical'|'Agrochemical'|'Hazardous'|'Pharmaceutical'|'Industrial';
type Network={name:string;scope:'Pan India'|'Regional';regions:string[];min_kg:number|null;max_kg:number|null;contact:string;email:string;source:string;evidence:string;note:string;cargo:string[]};

const NETWORK:Network[]=[
{name:'DNS Logistics',scope:'Pan India',regions:['North','West','South','East'],min_kg:1,max_kg:5000,contact:'+91 90827 36097',email:'info@dnslogistic.com',source:'https://www.dnslogistic.com/services/ptl',evidence:'Official PTL page',note:'18,000+ pincode PTL positioning; 24–72 hr published major-corridor TAT. Exact pincode and cargo acceptance still require quote/confirmation.',cargo:['General','Industrial','Pharmaceutical','Hazardous']},
{name:'Fast Trackon Logistics',scope:'Pan India',regions:['North','West','South','East'],min_kg:50,max_kg:5000,contact:'+91 88288 81414',email:'support@fasttrackonlogistics.com',source:'https://www.fasttrackonlogistics.com/services/ptl',evidence:'Official PTL page',note:'28,000+ pin codes, 500+ routes and 50 kg–5 tonne published PTL range; exact lane and cargo acceptance should be confirmed.',cargo:['General','Industrial']},
{name:'CTC India',scope:'Pan India',regions:['North','West','South','East'],min_kg:null,max_kg:null,contact:'+91 9873294018',email:'info@ctcipl.com',source:'https://www.ctcipl.com/services/part-truck-load-ptl',evidence:'Official PTL page',note:'Pan-India PTL routes are publicly listed; exact pincode and cargo acceptance should be confirmed.',cargo:['General','Industrial']},
{name:'Bombay Kandla Transport',scope:'Pan India',regions:['North','West','South','East'],min_kg:null,max_kg:null,contact:'sales@bombaykandla.com',email:'sales@bombaykandla.com',source:'https://bktpl.co.in/',evidence:'Official company site',note:'Pan-India road network with PTL and industrial freight positioning; exact lane should be confirmed.',cargo:['General','Industrial','Chemical']},
{name:'VRL Logistics',scope:'Pan India',regions:['North','West','South','East'],min_kg:null,max_kg:null,contact:'1800 599 7800',email:'customercare@vrllogistics.com',source:'https://www.vrlgroup.in/',evidence:'Official company site',note:'Publishes All India Parcel Service and General Parcel (LTL); use as a public network lead and confirm cargo acceptance.',cargo:['General','Industrial']},
{name:'TCI Express',scope:'Pan India',regions:['North','West','South','East'],min_kg:null,max_kg:null,contact:'Public contact via official site',email:'',source:'https://www.tciexpress.in/',evidence:'Official company site',note:'National express network lead; exact PTL/LTL lane and cargo acceptance should be confirmed.',cargo:['General','Industrial','Pharmaceutical']},
{name:'Gati',scope:'Pan India',regions:['North','West','South','East'],min_kg:null,max_kg:null,contact:'Public contact via official site',email:'',source:'https://www.gati.com/',evidence:'Official company site',note:'National surface logistics lead; verify exact PTL/LTL lane, weight and cargo acceptance.',cargo:['General','Industrial']},
{name:'Vidhi Transport',scope:'Regional',regions:['West'],min_kg:null,max_kg:null,contact:'+91 98253 21589',email:'customercare@vidhitransport.com',source:'https://vidhitransport.com/services/part-truck-load.html',evidence:'Official chemical/industrial PTL page',note:'Gujarat–Maharashtra GIDC/MIDC PTL; specifically publishes chemical and industrial freight handling. Acceptance is route/cargo dependent.',cargo:['General','Industrial','Chemical','Agrochemical']},
{name:'URTC Group',scope:'Regional',regions:['West','Central','East'],min_kg:null,max_kg:null,contact:'+91 97125 18095',email:'marketing@urtcgroup.com',source:'https://www.urtcgroup.com/services/part-load-transport-services/',evidence:'Official PTL page',note:'Regional part-load option covering Gujarat, Maharashtra, Odisha and Chhattisgarh corridors; verify exact pincode.',cargo:['General','Industrial']},
{name:'Superior Transways',scope:'Regional',regions:['West','North','South'],min_kg:null,max_kg:null,contact:'+91 7770026141',email:'superiortransways18@gmail.com',source:'https://superiortransways.com/part-load-transportation/',evidence:'Official PTL page',note:'Regional PTL network with West/North/South city coverage; verify exact lane.',cargo:['General','Industrial']},
{name:'Malwa Golden Logistics',scope:'Regional',regions:['North'],min_kg:null,max_kg:null,contact:'+91 94637 37337',email:'info@malwagolden.com',source:'https://www.malwagolden.com/',evidence:'Official company site',note:'Punjab/Haryana/Delhi-NCR PTL lead; verify exact destination pincode.',cargo:['General','Industrial']},
{name:'Mukund Logistics',scope:'Regional',regions:['North','Central'],min_kg:50,max_kg:5000,contact:'Public contact via official site',email:'',source:'https://mukundlogistic.com/ncr/services/part-load/',evidence:'Official part-load page',note:'NCR-focused PTL/LTL lead with published 50 kg–5 tonne positioning; verify exact lane.',cargo:['General','Industrial']}
];

const app=document.querySelector<HTMLDivElement>('#app')!;
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const fmt=(v:number|null|undefined)=>v==null?'—':Math.round(v).toLocaleString('en-IN');
const fmt1=(v:number|null|undefined)=>v==null?'—':v.toLocaleString('en-IN',{maximumFractionDigits:1});
const esc=(v:string)=>v.replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]!));
const fit=(q:number,min:number|null,max:number|null)=>(min==null||q>=min)&&(max==null||q<=max);
const pinRegion=(pin:string)=>{const n=Number(pin.charAt(0));return n<=2?'North':n<=4?'West':n<=6?'South':n<=8?'East':'Central'};
const cargoHelp=(cargo:Cargo)=>cargo==='Hazardous'?'Verify class-specific acceptance before any booking.':cargo==='Chemical'?'Chemical cargo: verify material, packaging, documents and route acceptance.':cargo==='Agrochemical'?'Agrochemical cargo: verify product classification, packaging and carrier acceptance.':cargo==='Pharmaceutical'?'Pharma cargo: confirm handling, temperature and documentation requirements.':'Standard PTL cargo: verify route and service terms.';
const cargoScore=(n:Network,c:Cargo)=>n.cargo.includes(c)?22:(c==='Hazardous'&&n.cargo.includes('Chemical')?10:4);
const regionScore=(n:Network,pick:string,drop:string)=>{const a=pinRegion(pick),b=pinRegion(drop);if(n.scope==='Pan India')return 30;const both=n.regions.includes(a)&&n.regions.includes(b);return both?30:(n.regions.includes(a)||n.regions.includes(b)?18:0)};

function shell(){
app.innerHTML=`<div class="shell"><aside class="side"><div class="brand"><b>◆ ATOMGRID</b><small>SMART TRANSPORT SOURCING</small></div><div class="nav active">Transporter Finder</div><div class="side-foot">Internal use only</div></aside><main class="main"><header class="top"><div><span class="kicker">SUPPLY CHAIN INTELLIGENCE</span><h2>Transporter Finder</h2></div><div class="live">● Live</div></header><section class="content"><div class="hero"><div><span class="eyebrow">HISTORICAL + ONLINE NETWORK</span><h1>Find transporter options for your lane.</h1><p>Atomgrid history stays the primary evidence. Public transporter leads are added by route region, quantity and cargo type.</p></div><div class="snapshot"><span>PTL shipments</span><strong id="ptl">—</strong><small id="meta">Loading base data…</small></div></div><section class="search"><label>Pickup Pincode<input id="pickup" maxlength="6" inputmode="numeric" placeholder="394116"></label><button id="swap" class="swap">↔</button><label>Delivery Pincode<input id="delivery" maxlength="6" inputmode="numeric" placeholder="502279"></label><label>Quantity (KG)<input id="qty" type="number" min="1" placeholder="850"></label><label>Cargo Type<select id="cargo"><option>General</option><option>Chemical</option><option>Agrochemical</option><option>Hazardous</option><option>Pharmaceutical</option><option>Industrial</option></select></label><button id="find" class="primary">Find Transporters <span>→</span></button></section><div class="smartbar"><div>✦</div><div><b>Smart sourcing</b><span>Exact lane → quantity fit → wider historical network → regional public leads → pan-India leads.</span></div><select id="mode"><option value="combined">Combined</option><option value="history">Historical only</option><option value="online">Online only</option></select></div><section class="summary" id="summary"></section><div class="section-head"><div><span class="eyebrow">RESULTS</span><h3 id="title">Enter a route, quantity and cargo</h3><p id="subtitle">Your sourcing options will appear here.</p></div><div class="count" id="count">0 options</div></div><div id="results"></div><div class="provenance"><b>Data basis:</b> historical results come from the Atomgrid Domestic MIS PTL history. Public options were checked against company websites and are leads—not proof of exact-pincode serviceability, rate or acceptance.</div></section></main></div>`;
$('find').addEventListener('click',search);$('swap').addEventListener('click',()=>{const p=$<HTMLInputElement>('pickup'),d=$<HTMLInputElement>('delivery');[p.value,d.value]=[d.value,p.value];search()});['pickup','delivery','qty'].forEach(id=>$(id).addEventListener('keydown',e=>{if((e as KeyboardEvent).key==='Enter')search()}));$('mode').addEventListener('change',search);$('cargo').addEventListener('change',search);
}

async function load(){try{const r=await fetch('/api/data');if(!r.ok)throw new Error(`HTTP ${r.status}`);const b=await r.json() as Base;$('ptl').textContent=fmt(b.meta.ptl_shipments);$('meta').textContent=`${b.meta.transporters} transporters • ${b.meta.exact_pincode_lanes} exact lanes`;(window as any).BASE=b;renderEmpty()}catch(e){console.error(e);$('meta').textContent='Base dataset unavailable';$('results').innerHTML='<div class="empty">The historical MIS could not be loaded. Please retry in a moment.</div>';}}
function renderEmpty(){ $('summary').innerHTML='';$('results').innerHTML='<div class="empty">Enter pickup pincode, delivery pincode and quantity to see transporter options.</div>';}

function scoreLane(l:Lane,q:number,maxS:number,maxD:number){return Math.round(Math.min(100,45+(fit(q,l.min_qty_kg,l.max_qty_kg)?25:0)+(maxS?20*l.shipments/maxS:0)+(l.avg_tat_days!=null?Math.max(1,8-l.avg_tat_days):2)+(maxD&&l.avg_distance_km!=null?Math.max(1,5-3*l.avg_distance_km/maxD):2)))}
function historicalCard(l:Lane,q:number,score:number,warning:boolean,rank:number){return `<div class="card ${warning?'':'featured'}"><div class="rank">#${rank}</div><div class="row"><div><h4>${esc(l.transporter)}</h4><p>Atomgrid historical PTL movement</p></div><div class="score"><b>${score}</b><span>FIT<br>SCORE</span></div></div><div class="badges"><span class="badge blue">${l.shipments} shipments</span><span class="badge ${warning?'amber':'green'}">${warning?'Quantity outside history':'Quantity fits history'}</span><span class="badge">Exact pincode lane</span></div><div class="metrics"><span><small>TAT</small><b>${fmt1(l.median_tat_days??l.avg_tat_days)} days</b></span><span><small>Distance</small><b>${fmt(l.avg_distance_km)} km</b></span><span><small>History range</small><b>${fmt(l.min_qty_kg)}–${fmt(l.max_qty_kg)} KG</b></span><span><small>Last used</small><b>${esc(l.last_used??'—')}</b></span></div><div class="why"><b>Why shown</b><span>${warning?'Exact historical lane, but requested quantity is outside observed shipment range.':'Exact pickup → delivery lane with historical usage.'}</span><span>Use historical TAT only as a planning reference.</span></div></div>`}
function networkCard(n:Network,q:number,c:Cargo,pick:string,drop:string,score:number,rank:number){const rg=`${pinRegion(pick)} → ${pinRegion(drop)}`,cf=n.cargo.includes(c);return `<div class="card online-card"><div class="rank">#${rank}</div><div class="row"><div><h4>${esc(n.name)}</h4><p>${n.scope} public-network lead • ${rg}</p></div><div class="score green-score"><b>${score}</b><span>NETWORK<br>FIT</span></div></div><div class="badges"><span class="badge green">${n.scope}</span><span class="badge ${cf?'green':'amber'}">${cf?`Published ${c.toLowerCase()} relevance`:'Cargo acceptance: verify'}</span>${fit(q,n.min_kg,n.max_kg)?'<span class="badge blue">Weight fits published range</span>':''}</div><div class="metrics"><span><small>Coverage</small><b>${n.regions.join(', ')}</b></span><span><small>Weight</small><b>${n.min_kg!=null||n.max_kg!=null?`${fmt(n.min_kg)}–${fmt(n.max_kg)} KG`:'Not published'}</b></span><span><small>Contact</small><b>${esc(n.contact)}</b></span><span><small>Evidence</small><b>${esc(n.evidence)}</b></span></div><div class="why"><b>Why shown</b><span>${regionScore(n,pick,drop)>18?'Route region matches the published network.':'Pan-India or wider-network fallback.'}</span><span>${n.note}</span><span>${cargoHelp(c)}</span></div><div class="foot"><span>${n.email?esc(n.email):'Public website contact'}</span><a href="${n.source}" target="_blank" rel="noreferrer">Open source →</a></div></div>`}

function search(){
const base=(window as any).BASE as Base;if(!base)return;
const p=$<HTMLInputElement>('pickup').value.trim(),d=$<HTMLInputElement>('delivery').value.trim(),q=Number($<HTMLInputElement>('qty').value||0),cargo=$<HTMLSelectElement>('cargo').value as Cargo,mode=$<HTMLSelectElement>('mode').value;
if(!/^\d{6}$/.test(p)||!/^\d{6}$/.test(d)||q<=0){renderEmpty();return}
const pickupRegion=pinRegion(p),dropRegion=pinRegion(d);
const exact=base.lanes.filter(x=>x.pickup===p&&x.delivery===d);
const exactFit=exact.filter(x=>fit(q,x.min_qty_kg,x.max_qty_kg)).sort((a,b)=>b.shipments-a.shipments);
const exactWarn=exact.filter(x=>!fit(q,x.min_qty_kg,x.max_qty_kg)).sort((a,b)=>b.shipments-a.shipments);
const maxS=Math.max(1,...exact.map(x=>x.shipments));const maxD=Math.max(1,...exact.map(x=>x.avg_distance_km||0));
const histOnly=base.transporters.map(t=>{const lanes=base.lanes.filter(l=>l.transporter===t.name);const matching=lanes.filter(l=>fit(q,l.min_qty_kg,l.max_qty_kg));const sameRegion=lanes.some(l=>pinRegion(l.pickup)===pickupRegion||pinRegion(l.delivery)===dropRegion);return {t,lanes,matching,sameRegion}}).filter(x=>x.lanes.length).sort((a,b)=>((b.matching.reduce((s,l)=>s+l.shipments,0)+(b.sameRegion?8:0))-(a.matching.reduce((s,l)=>s+l.shipments,0)+(a.sameRegion?8:0)))).slice(0,8);
const online=NETWORK.map(n=>{let s=45+regionScore(n,p,d)+cargoScore(n,cargo);if(fit(q,n.min_kg,n.max_kg))s+=12;else if(n.min_kg!=null||n.max_kg!=null)s-=4;return {...n,score:Math.min(99,s)}}).sort((a,b)=>b.score-a.score);
const sections:string[]=[];
if(mode!=='online'&&exactFit.length)sections.push(`<div class="tag hist">ATOMGRID HISTORICAL — EXACT LANE</div>${exactFit.slice(0,8).map((l,i)=>historicalCard(l,q,scoreLane(l,q,maxS,maxD),false,i+1)).join('')}`);
if(mode!=='online'&&exactWarn.length)sections.push(`<div class="tag warn">ATOMGRID HISTORICAL — QUANTITY OUTSIDE RANGE</div>${exactWarn.slice(0,6).map((l,i)=>historicalCard(l,q,scoreLane(l,q,maxS,maxD),true,i+1)).join('')}`);
if(mode!=='online'&&!exact.length){sections.push(`<div class="tag hist">ATOMGRID HISTORICAL — WIDER NETWORK</div>${histOnly.slice(0,6).map((x,i)=>{const l=x.matching[0]||x.lanes[0];const pseudo={...l,pickup:l.pickup,delivery:l.delivery,transporter:x.t.name,shipments:x.matching.reduce((s,z)=>s+z.shipments,0)||x.t.shipments};return historicalCard(pseudo,q,Math.min(88,50+(x.sameRegion?15:0)+(x.matching.length?20:0)+Math.min(15,x.t.shipments/10)),false,i+1).replace('Exact pincode lane','Wider historical network')} ).join('')}`)}
if(mode!=='history')sections.push(`<div class="tag online">PUBLIC NETWORK — REGIONAL + PAN INDIA</div>${online.slice(0,10).map((n,i)=>networkCard(n,q,cargo,p,d,n.score,i+1)).join('')}`);
const total=sections.join('');
$('title').textContent=`${p} → ${d}`;$('subtitle').textContent=`${pickupRegion} → ${dropRegion} • ${fmt(q)} KG • ${cargo}`;$('count').textContent=`${(mode==='history'?Math.min(14,exactFit.length+exactWarn.length+(exact.length?0:histOnly.length)):mode==='online'?Math.min(10,online.length):Math.min(20,exactFit.length+exactWarn.length+(exact.length?0:histOnly.length)+online.length))} options`;
$('summary').innerHTML=`<div class="summary-icon">✦</div><div><b>SOURCING SIGNAL</b><strong>${exactFit.length?`${exactFit.length} historical transporter option${exactFit.length>1?'s':''} fit the requested quantity.`:exact.length?`${exact.length} historical transporter${exact.length>1?'s':''} used this exact lane, but none match the requested quantity range.`:'No exact historical lane found, so wider history and public network leads are shown.'}</strong><span>${cargoHelp(cargo)} Public providers below are route/cargo leads and should be confirmed before dispatch.</span></div>`;
$('results').innerHTML=total||'<div class="empty">No options matched the current filters.</div>';
}

shell();load();
